baseurl = "https://itslab-kyushu.github.io/simple-kvs/"
languageCode = "en-us"
metadataformat = "yaml"
title = "Simple Key-Value Datastore service"
theme = "hugo-alabaster-theme"

disqusShortname = ""
googleAnalytics = "UA-89247555-1"

[params]
	name = "simple-kvs"
	description = "Key-Value Datastore service"

	github_user   = "itslab-kyushu"
	github_repo   = "simple-kvs"
	github_banner = true

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"

	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = "~jkawamoto"

	show_relations = false

[params.footer]
	copyright = "[Junpei Kawamoto](https://github.com/jkawamoto/) | Icon by [Clipart Kid](http://www.clipartkid.com/)"
	show_powered_by = true
